# -*- coding: utf-8 -*-
"""AkashThiruveedula.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VI5VzjYrpU9BAl-b3rvmTEJGn-vGuiXX
"""

print("Hello world")


#sum of two numbers
a = int(input(" enter a number "))
b = int(input(" enter b number "))
print("sum of the two numbers",a+b)

#squareroot of the number
import math
a=int(input("enter the number"))
print(math.sqrt(a))

#area of the triangle
b=int(input("enter the breadth "))
h=int(input("enter the height"))
print("area of the triangle",0.5*b*h)

#solving a quadrative
import math

A=int(input("enter the number"))
B=int(input("enter the number"))
C=int(input("enter the number"))

eq = (B**2)-(4*A*C)

eq_sol1 = (-B + math.sqrt(eq))/(2*A)
eq_sol2 = (-B - math.sqrt(eq))/(2*A)

print(eq_sol1)
print(eq_sol2)

x = int(input("enter the number x"))
y = int(input("enter the number y"))

n=x
x=y
y=n

print("the swapped number of x",x)
print("the swapped number of y",y)

#print random numbers
import random 
num = random.random()
print(num)

#convert kilometer to miles
k = int(input("enter the kilometer value"))
mile = k*0.62137119
print("the value of kilometer in miles is",mile)

#celsius to fahrenheit
F = int(input("enter the value to be changed to celsius"))
celsius =(F-32)/1.8
print("the value in celsius is ",celsius)

num = float(input("enter the number :"))
if num>0:
  print("+ve number")
elif num<0:
  print("-ve number")
else:
  print("zero")

#check a number is odd or even
num = int(input("Enter a number: "))
if (num % 2) == 0:
   print("{0} is Even".format(num))
else:
   print("{0} is Odd".format(num))

# check if it is a leap year or not
year = 2022


if (year % 400 == 0) and (year % 100 == 0):
    print("{0} is a leap year".format(year))

elif (year % 4 ==0) and (year % 100 != 0):
    print("{0} is a leap year".format(year))
else:
    print("{0} is not a leap year".format(year))

#greatest of three numbers
n1 = int(input("enter the 1st number "))
n2 = int(input("enter the 2nd number "))
n3 = int(input("enter the 3rd number "))

if (n1>n2  and n1>n3):
  print("the largest of the three numbers is",n1)
elif (n2>n1 and n2>n3):
  print("the largest of the three numbers is",n2)
else:
  print("the largest of the three numbers is",n3)

num = int(input("enter the number"))

if num > 1:

	for i in range(2, int(num/2)+1):

		if (num % i) == 0:
			print(num, "is not a prime number")
			break
	else:
		print(num, "is a prime number")

else:
	print(num, "is not a prime number")

first = int(input("enter the first number"))
last = int(input("enter the last number"))
print("Prime numbers from ",first,"to",last, "are:")

for num in range(first,last  + 1):
   if num > 1:
       for i in range(2, num):
           if (num % i) == 0:
               break
       else:
           print(num)

fact = int(input("enter the number"))
n=1
for i in range(1,fact+1):
  n=n*i
print("the factorial of the number is",n)

n = int(input("enter the number"))

n1, n2 = 0, 1
x = 0

if n <= 0:
   print("error")
else:
   print("Fibonacci sequence:")
   while x < n:
       print(n1)
       a = n1 + n2
       n1 = n2
       n2 = a
       x += 1

g = int(input ("enter the table number"))
for i in range(1,g+1):
  print(g,"x",i,"=",g*i)

#Program for performing arithmetic operation
a1=float(input("enter the number a : "))
a2=float(input("enter the number b : "))

print("the addition of the two numbers is",a1+a2)
print("the subtraction of the two numbers is",a1-a2)
print("the multiplication of the two numbers is",a1*a2)
print("the floating division of the two numbers is",a1/a2)
print("the exponential of the two numbers is",a1**a2)
print("the integer division of the two numbers is",a1//a2)
print("the reminder of the two numbers is",a1%a2)

#2. Program for performing relational operation
a1=float(input("enter the number a : "))
a2=float(input("enter the number b : "))

print("the greater than of the two numbers is",a1>a2)
print("the less than of the two numbers is",a1<a2)
print("the equal to of the two numbers is",a1==a2)
print("the not equal to of the two numbers is",a1!=a2)
print("the greater than or equal of the two numbers is",a1>=a2)
print("the less than or equal to of the two numbers is",a1<=a2)

#3. Program for performing logical operation
b1=float(input("enter the number x : "))

print("and operator",(b1<5 and b1<10))
print("or operator",(b1<5 or b1<10))
print("not operator",not(b1<5 and b1<10))

#4. Program for performing short hand assignment operation
x=int(input("enter the number:"))
y=int(input("enter the number:"))
x+=y
print(x)

#5.Program for equality and inequality checking
x=int(input("enter the number:"))
y=int(input("enter the number:"))
if(x==y):
  print("True")
else:
  print("False")

#Write a program to accept a string and display it in upper case
z=input("enter a string name :")
print(z.upper())

#Write a program to accept a string and display the ascii value of each character
q=input("enter a string:")
for i in q:
  print(ord(i))

n=5
for t in range(1,n+1):
  for q in range(1,t+1):
    print(t,end="")
  print()

n='*'
for i in range(1,6):
 for j in range(1,i+1):
     print(n,end="")
 print()

n=1
for i in range(5):
    for j in range(i+1):
         print(n,end=" ")
         n=n+1
    print()

value = 65
for i in range(0,5):
  for j in range(0,i+1):
    ar=chr(value)
    print(ar,end="")
  value+=1
  print()

test_string = "ironman"
mac_fex ={}
for i in test_string:
  if i in mac_fex:
    mac_fex[i] +=1
  else:
    mac_fex[i] =1

print("count all character"+str(mac_fex))

def change_char(str1):
  char=str1[0]
  str1=str1.replace(char,"#")
  str1=char+str1[1:]
  return str1
print(change_char("krithika"))

#Write a program to display the unique words from the string
import re
dict = {}
def uniqueWord(Word):
  if Word in dict:
     dict[words] += 1
  else:
     dict.update({words: 1})

if __name__ == '__main__':
  string = "python,python programming"
  ListOfWords = re.split("[\W]+", string)
  for words in ListOfWords:
     uniqueWord(words)
     for elements in dict:
        if dict[elements] == 1:
            print(elements)

#Write a program to accept a string and display the string in Title case.
l=input("Enter a string:")
print(l.title())

#Write a program to accept a string and replace all spaces by ‘#’ symbol.
f=input("Enter a string:")
f=f.replace(" ","#")
print(f)

#Write a program to accept two strings from the user and display the common words.(Ignore c
r1=input("Enter a string:")
r2=input("Enter a string:")
a=list(set(r1) and set(r2))
for i in a:
  print(i)

#Write a program to accept a string and count the frequency of each vowel
def check_vow(string,vowels):
    final=[each for each in string if each in vowels]
    print(final)
string="play with paint"
vowels="AaEeIiOoUu"
check_vow(string,vowels)

#Write a Python program to get the volume of a sphere with radius 6.
r=6
volume=(4/3)*3.14*r*r*r
print(volume)

#Write a Python program which accepts the radius of a circle from the user and compute the
r=int(input("Enter the radius:"))
area=4*3.14*r
print(area)

#. Write a Python program to find the median among three given number
num1 = float(input("Input first number: "))
num2 = float(input("Input second number: "))
num3 = float(input("Input third number: "))
if num1 > num2:
    if num1 < num3:
      median = num1
    elif b > num3:
      median = num2
    else:
      median = num3
else:
    if num1 > num3:
       median = num1
    elif num2 < num3:
       median = num2
    else:
       median = num3
print("The median is", median)
